os:
  - linux

dist: xenial

language: php

php:
  - 7.2
  - 7.3
  - master

matrix:
  allow_failures:
    - php: master
      
before_install:
  - if [ ! -d $HOME/.phive ]; then mkdir $HOME/.phive ; fi
  - if [ ! -f $HOME/.phive/phive.phar ]; then ant travis-install-phive ; mv phive.phar $HOME/.phive
    ; fi
  - sudo cp $HOME/.phive/phive.phar /usr/local/bin/phive

install:
  - phive --no-progress install phpunit --trust-gpg-keys 4AA394086372C20A

script: "./tools/phpunit"

notifications:
  email: false
  
